projet Projet PDB 2526
charger Charger
sauver Sauver
cr\u00e9er Cr\u00e9ez...
inst.existePas Cette installation n'existe pas
inst.id Entrez l'id de l'installation

titre.piece.creer Cr\u00e9ation d'une Piece
piece.nom Nom
piece.description Description
piece.etage Etage
piece.typePiece Type de pi\u00e8ce
piece.titre Piece

piece.liste.titre Liste des pi\u00e8ces
operation Op\u00e9ration

action.ok Valider
action.add Ajout
action.maj Mise \u00e0 Jour
action.del Supprimer
action.quitter Quitter
action.save Sauver
action.check V\u00e9rification
action.reload Recharger
action.annuler Annuler
action.charger Charger

ctx.addPiece Ajoute une pi\u00e8ce
ctx.delPiece Supprime une pi\u00e8ce

err.noInstall Pas d'installation charg\u00e9e
err.install.inconnue Installation inconnue!
err.update La mise \u00e0 jour n'a pas fonctionn\u00e9
err.nbr Il faut entrer un nombre!
err.suppression.impossible Suppression impossible
err.insertion.impossible Insertion impossible
err.mise_a_jour.impossible Mise \u00e0 jour impossible

bt.load Charger une Installation
bt.cree.piece Cr\u00e9e une Pi\u00e8ce
bt.liste.piece Liste des Pi\u00e8ces
bt.element \u00c9l\u00e9ments
bt.schema Sch\u00e9ma \u00e9tage

conf.save Voulez-vous sauver les modifications ?
err.save Erreur lors de la sauvegarde