-- INSTALLATION 1
INSERT INTO TINSTALLATION (NUM_INS, DATE_INS, ADRESSE_INS, CP_INS, VILLE_INS, INSTALLATEUR_INS, PROPRIETAIRE_INS)
VALUES (1, '2026-01-15', 'Rue de la Paix 10', 1000, 'Bruxelles', 'ABV', 'P001');

INSERT INTO TPLAN (NOM_PLA, FKINSTALLATION_PLA) VALUES ('Rez de chaussée', 1);

INSERT INTO TPIECE (NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE, FKINSTALLATION_PIE)
VALUES ('Salon', 'Salon principal', 0.0, 'SALON', 1);

INSERT INTO TPIECE (NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE, FKINSTALLATION_PIE)
VALUES ('Salle de bain', 'Salle de bain', 1.0, 'SDB', 1);

-- INSTALLATION 2
INSERT INTO TINSTALLATION (NUM_INS, DATE_INS, ADRESSE_INS, CP_INS, VILLE_INS, INSTALLATEUR_INS, PROPRIETAIRE_INS)
VALUES (2, '2026-02-20', 'Avenue Louise 200', 1050, 'Bruxelles', 'ABV', 'P002');

INSERT INTO TPLAN (NOM_PLA, FKINSTALLATION_PLA) VALUES ('Premier étage', 2);

INSERT INTO TPIECE (NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE, FKINSTALLATION_PIE)
VALUES ('Living', 'Pièce à vivre', 0.0, 'LIVING', 2);

INSERT INTO TPIECE (NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE, FKINSTALLATION_PIE)
VALUES ('Salle à manger', 'Salle à manger', 0.0, 'SAM', 2);