
--Vide les tables
DELETE FROM TPIECE;
ALTER TABLE TPIECE ALTER NUM_PIE restart with 1;
DELETE FROM TTYPE_PIECE;

--Encode les données dans la base de données de test
--TTYPEPIECE
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('SALON','Salon',false);
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('LIVING','Living',false);
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('SDB','Salle de bain',true);
INSERT INTO TTYPE_PIECE (CODE_TYP, NOM_TYP, HUMIDE_TYP) VALUES('SAM','Salle à manger',false);
--Piece
INSERT INTO TPIECE ( NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE,FKINSTALLATION_PIE)
VALUES ('SALON','Salon principal', 0, 'SALON', 3);
INSERT INTO TPIECE ( NOM_PIE, DESCRIPTION_PIE, ETAGE_PIE, FKTYPE_PIE,FKINSTALLATION_PIE)
VALUES ('Salle à manger','Salle à manger principal', 0, 'SAM', 3);

